// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnI35s2CP2RBTF_ocAbECM697WN5gFzYc',
    appId: '1:616858364446:web:c84dda13aa69db83bbdc0f',
    messagingSenderId: '616858364446',
    projectId: 'inventoryapp-3698c',
    authDomain: 'inventoryapp-3698c.firebaseapp.com',
    storageBucket: 'inventoryapp-3698c.firebasestorage.app',
    measurementId: 'G-XXXXXXXXXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnI35s2CP2RBTF_ocAbECM697WN5gFzYc',
    appId: '1:616858364446:android:c84dda13aa69db83bbdc0f',
    messagingSenderId: '616858364446',
    projectId: 'inventoryapp-3698c',
    storageBucket: 'inventoryapp-3698c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnI35s2CP2RBTF_ocAbECM697WN5gFzYc',
    appId: '1:616858364446:ios:c84dda13aa69db83bbdc0f',
    messagingSenderId: '616858364446',
    projectId: 'inventoryapp-3698c',
    storageBucket: 'inventoryapp-3698c.firebasestorage.app',
    iosBundleId: 'com.example.inventoryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnI35s2CP2RBTF_ocAbECM697WN5gFzYc',
    appId: '1:616858364446:ios:c84dda13aa69db83bbdc0f',
    messagingSenderId: '616858364446',
    projectId: 'inventoryapp-3698c',
    storageBucket: 'inventoryapp-3698c.firebasestorage.app',
    iosBundleId: 'com.example.inventoryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnI35s2CP2RBTF_ocAbECM697WN5gFzYc',
    appId: '1:616858364446:web:c84dda13aa69db83bbdc0f',
    messagingSenderId: '616858364446',
    projectId: 'inventoryapp-3698c',
    authDomain: 'inventoryapp-3698c.firebaseapp.com',
    storageBucket: 'inventoryapp-3698c.firebasestorage.app',
    measurementId: 'G-XXXXXXXXXX',
  );
}
